package Project.Uml;

/**
* Project/Uml/DiagramHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UML.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public final class DiagramHolder implements org.omg.CORBA.portable.Streamable
{
  public Project.Uml.Diagram value = null;

  public DiagramHolder ()
  {
  }

  public DiagramHolder (Project.Uml.Diagram initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Project.Uml.DiagramHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Project.Uml.DiagramHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Project.Uml.DiagramHelper.type ();
  }

}
