package Project.Uml;


/**
* Project/Uml/TypeAssociation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UML.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public class TypeAssociation implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static Project.Uml.TypeAssociation[] __array = new Project.Uml.TypeAssociation [__size];

  public static final int _include = 0;
  public static final Project.Uml.TypeAssociation include = new Project.Uml.TypeAssociation(_include);
  public static final int _extend = 1;
  public static final Project.Uml.TypeAssociation extend = new Project.Uml.TypeAssociation(_extend);
  public static final int _generalization = 2;
  public static final Project.Uml.TypeAssociation generalization = new Project.Uml.TypeAssociation(_generalization);

  public int value ()
  {
    return __value;
  }

  public static Project.Uml.TypeAssociation from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TypeAssociation (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TypeAssociation
