package Project.Uml;

/**
* Project/Uml/TypeAssociationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UML.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public final class TypeAssociationHolder implements org.omg.CORBA.portable.Streamable
{
  public Project.Uml.TypeAssociation value = null;

  public TypeAssociationHolder ()
  {
  }

  public TypeAssociationHolder (Project.Uml.TypeAssociation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Project.Uml.TypeAssociationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Project.Uml.TypeAssociationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Project.Uml.TypeAssociationHelper.type ();
  }

}
