package Project.Uml;

/**
* Project/Uml/UMLAssociationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UML.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public final class UMLAssociationHolder implements org.omg.CORBA.portable.Streamable
{
  public Project.Uml.UMLAssociation value = null;

  public UMLAssociationHolder ()
  {
  }

  public UMLAssociationHolder (Project.Uml.UMLAssociation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Project.Uml.UMLAssociationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Project.Uml.UMLAssociationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Project.Uml.UMLAssociationHelper.type ();
  }

}
