package Project.Uml;


/**
* Project/Uml/UMLAssociation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UML.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public final class UMLAssociation implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String nome = null;
  public Project.Uml.UMLElement a = null;
  public Project.Uml.UMLElement b = null;

  public UMLAssociation ()
  {
  } // ctor

  public UMLAssociation (String _id, String _nome, Project.Uml.UMLElement _a, Project.Uml.UMLElement _b)
  {
    id = _id;
    nome = _nome;
    a = _a;
    b = _b;
  } // ctor

} // class UMLAssociation
