package Project.Uml;

/**
* Project/Uml/UMLElementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UML.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public final class UMLElementHolder implements org.omg.CORBA.portable.Streamable
{
  public Project.Uml.UMLElement value = null;

  public UMLElementHolder ()
  {
  }

  public UMLElementHolder (Project.Uml.UMLElement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Project.Uml.UMLElementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Project.Uml.UMLElementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Project.Uml.UMLElementHelper.type ();
  }

}
