package Project.Uml;


/**
* Project/Uml/UMLElement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UML.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public final class UMLElement implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;
  public String nome = null;

  public UMLElement ()
  {
  } // ctor

  public UMLElement (String _id, String _nome)
  {
    id = _id;
    nome = _nome;
  } // ctor

} // class UMLElement
