package ExampleParser;


/**
* ExampleParser/Parser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Parser.idl
* Sexta-feira, 5 de Maio de 2017 02H11m BRT
*/

public interface Parser extends ParserOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Parser
