package ExampleParser;

/**
* ExampleParser/ParserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Parser.idl
* Sexta-feira, 5 de Maio de 2017 02H11m BRT
*/

public final class ParserHolder implements org.omg.CORBA.portable.Streamable
{
  public ExampleParser.Parser value = null;

  public ParserHolder ()
  {
  }

  public ParserHolder (ExampleParser.Parser initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ExampleParser.ParserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ExampleParser.ParserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ExampleParser.ParserHelper.type ();
  }

}
