package Project.ExampleParser;

/**
* Project/ExampleParser/ParserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Parser.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public final class ParserHolder implements org.omg.CORBA.portable.Streamable
{
  public Project.ExampleParser.Parser value = null;

  public ParserHolder ()
  {
  }

  public ParserHolder (Project.ExampleParser.Parser initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Project.ExampleParser.ParserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Project.ExampleParser.ParserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Project.ExampleParser.ParserHelper.type ();
  }

}
