package Project.ExampleParser;


/**
* Project/ExampleParser/ParserHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Parser.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

abstract public class ParserHelper
{
  private static String  _id = "IDL:Project/ExampleParser/Parser:1.0";

  public static void insert (org.omg.CORBA.Any a, Project.ExampleParser.Parser that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Project.ExampleParser.Parser extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Project.ExampleParser.ParserHelper.id (), "Parser");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Project.ExampleParser.Parser read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ParserStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Project.ExampleParser.Parser value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Project.ExampleParser.Parser narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Project.ExampleParser.Parser)
      return (Project.ExampleParser.Parser)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Project.ExampleParser._ParserStub stub = new Project.ExampleParser._ParserStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Project.ExampleParser.Parser unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Project.ExampleParser.Parser)
      return (Project.ExampleParser.Parser)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Project.ExampleParser._ParserStub stub = new Project.ExampleParser._ParserStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
