package Project.ExampleParser;


/**
* Project/ExampleParser/ParserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Parser.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public interface ParserOperations 
{

  //Metodo de gerenciamento do Parser responsável pela criacao dos diagramas insercao de elementos e ligacao dos diagramas com os UC.
  void managerParser (String path);

  //Metodos de adicao de elementos no diagrama de casos de uso.
  Project.Uml.UMLElement addActor (int partialDoc);
  Project.Uml.UMLAssociation addAssociation ();
  Project.Uml.TypeAssociation addInclude ();
  boolean addExtend ();
  boolean addUseCase ();

  //Metodos de adicao do elemento decisionNode  Recebe o parametro tipo, pois ambos diagramas podem conter.
  boolean addDecisionNode ();

  //Metodos de criacao e adicao de elementos do diagrama de atividades criado.
  boolean addInitAction ();
  boolean addFinalAction ();
  boolean addAction ();
  boolean addFork ();
  boolean addJoin ();

  //Metodo para adicao de um novo diagrama à lista de diagramas, diferenciando o tipo do diagrama.
  boolean addDiagram ();

  //Metodo para buscar um diagrama na lista
  void getDiagram ();
} // interface ParserOperations
