package Project.ExampleParser;


/**
* Project/ExampleParser/Parser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Parser.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public interface Parser extends ParserOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Parser
