package Project.exceptions;


/**
* Project/exceptions/ElementNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Exceptions.idl
* Segunda-feira, 22 de Maio de 2017 15H01m BRT
*/

public final class ElementNotFound extends org.omg.CORBA.UserException
{

  public ElementNotFound ()
  {
    super(ElementNotFoundHelper.id());
  } // ctor


  public ElementNotFound (String $reason)
  {
    super(ElementNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class ElementNotFound
